security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory_provider:
            id: crm.in_memory_user_repository

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/admin
            stateless: true
            simple_preauth:
                authenticator: crm.authenticator

    access_control:
        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }